import turtle

turtle.shape("turtle")
a = 100
color_1 = "red"
color_2 = "blue"
turtle.pencolor(color_1)
turtle.fd(a)
turtle.lt(120)
turtle.fd(a)
turtle.rt(48)
turtle.pencolor(color_2)
turtle.fd(a)
turtle.lt(120)
turtle.fd(a)
turtle.rt(48)
turtle.pencolor(color_1)
turtle.fd(a)
turtle.lt(120)
turtle.fd(a)
turtle.rt(48)
turtle.pencolor(color_2)
turtle.fd(a)
turtle.lt(120)
turtle.fd(a)
turtle.rt(48)
turtle.pencolor(color_1)
turtle.fd(a)
turtle.lt(120)
turtle.fd(a)
turtle.rt(48)
