import turtle

turtle.shape("turtle")
length = 100
red_color = "red"
blue_color = "blue"
turtle.pencolor(red_color)
turtle.fd(length)
turtle.lt(120)
turtle.fd(length)
turtle.rt(48)
turtle.pencolor(blue_color)
turtle.fd(length)
turtle.lt(120)
turtle.fd(length)
turtle.rt(48)
turtle.pencolor(red_color)
turtle.fd(length)
turtle.lt(120)
turtle.fd(length)
turtle.rt(48)
turtle.pencolor(blue_color)
turtle.fd(length)
turtle.lt(120)
turtle.fd(length)
turtle.rt(48)
turtle.pencolor(red_color)
turtle.fd(length)
turtle.lt(120)
turtle.fd(length)
turtle.rt(48)
